### ISSUE TITLE
The recordset's repr() changes and is misleading

### ISSUE THREAD

**Issue by yajo** [trinhanhngoc/pydevd-odoo#1]
Look at how `self` looks in VSCode without the plugin:

![2020-10-21_10-02](https://user-images.githubusercontent.com/973709/96698533-86558480-138d-11eb-90ca-611a7f3617e8.png)

With it:

![2020-10-21_10-06](https://user-images.githubusercontent.com/973709/96698537-86ee1b00-138d-11eb-888a-c19b406ea75b.png)

As said in https://github.com/Tecnativa/doodba/pull/333#issuecomment-713426058, the fact that `self` becomes `[1, 2, 3]` instead of `stock.warehouse(1, 2, 3)` is misleading, as it makes the variable look like it's a `list` instead of a recordset.

I wonder if that can be left as it was, without impacting the other niceties of this plugin.

**Comment by ntvsp** [comment]
a ngọc làm plugin cho vscode rồi à

**Comment by yajo** [comment]
Where is it?

**Comment by cuongnmtm** [comment]
@Yajo: tuanvuvd said that the author finally created the plugin for vscode. It's like a rhetorical question

**Comment by gdgellatly** [comment]
@cuongnmtm Yes we understand it works for VSCode, it was more why the repr() output disappears in VSCode. In the first screenshot you clearly see the repr() representation (without this plugin), in the screenshot in the README.md for this plugin you clearly see the repr() representation with the name, in the screenshot above, in VSCode there is no repr(). i.e. `2: {stock.warehouse: 3} [3] Chicago` or similar

**Comment by cuongnmtm** [comment]
@gdgellatly I tried to translate for Yajo

BTW, I like the way @trinhanhngoc adjusted repr() to show the record name. It's especially useful in case there are relationship fields inside

![image](https://user-images.githubusercontent.com/32898439/96997372-dbdf8c00-155b-11eb-94b7-c0e825103cff.png)

**Comment by cuongnmtm** [comment]
@Yajo @gdgellatly My pull request was merged. Could you please check the result? I think this issue is ok to close

**Comment by yajo** [comment]
Yes, pretty cool, thanks!

![imagen](https://user-images.githubusercontent.com/973709/97157258-276e8180-1778-11eb-8115-4b60e7f6a637.png)
