### ISSUE TITLE
Pydevd-odoo does not work for Python 3.8 

### ISSUE THREAD

**Issue by joao-p-marques** [trinhanhngoc/pydevd-odoo#3]
When I try to run `pydevd-odoo` in Python 3.8 along with `debugpy`, it introduces an error that prevents it from running

The error is the following:
```bash
root@631a7db35ba5:/# python -m debugpy -h
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/debugpy/__main__.py", line 43, in <module>
    from debugpy.server import cli
  File "/usr/local/lib/python3.8/site-packages/debugpy/server/__init__.py", line 9, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "/usr/local/lib/python3.8/site-packages/debugpy/_vendored/force_pydevd.py", line 14, in <module>
    _unvendored, _ = check_modules('pydevd',
  File "/usr/local/lib/python3.8/site-packages/debugpy/_vendored/__init__.py", line 106, in check_modules
    elif not mod.__file__.startswith(root):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I associate this bug with `pydev-odoo` because:

![image](https://user-images.githubusercontent.com/38977934/98655861-dfcf2480-2337-11eb-9e2f-041abf408d05.png)

cc @Tecnativa @Yajo

**Comment by gdgellatly** [comment]
https://github.com/microsoft/debugpy/issues/475 crosslink

**Comment by gdgellatly** [comment]
@joao-p-marques Please see https://github.com/fabioz/debugpy/commit/792458b2c666f3bb254781834f0c379c1a143e09 . 

Seems it is not an issue with this module, but ratther pydevd.

**Comment by joao-p-marques** [comment]
Thanks @gdgellatly. I will test if that fixes the issue.

My only question is why did installing `pydevd-odoo` trigger the issue? `pydevd` should already come from `debugpy` right? Does this have to do with some specific `pydevd` version that `pydevd-odoo` installs?

**Comment by gdgellatly** [comment]
@joao-p-marques No it is nothing like that. It is simply that you happened to install a pydevd extension. If it wasn't this module it would have been another. The error is in the extension loading mechanism of pydevd. Looking at the failing code it is quite obviously a pydevd issue and not to do with this module.

**Comment by gdgellatly** [comment]
@joao-p-marques I have checked and this issue was closed upstream by this commit https://github.com/microsoft/debugpy/commit/ac05dab62b1df63c52cc1219fc335b456acaab3a
