### ISSUE TITLE
can't excute python sentence in console

### ISSUE THREAD

**Issue by ohplz** [trinhanhngoc/pydevd-odoo#4]
![image](https://user-images.githubusercontent.com/46417244/201566193-ec7007e4-a4bb-489c-b6ea-0dca5ba236f9.png)

**Comment by trinhanhngoc** [comment]
Hi @ohplz 

I'm not sure what the problem is here. Can you provide more information?

**Comment by ohplz** [comment]
sure, sry not to offer more info earlier~

I'm using pycharm as IDE, and running Odoo in debug mode, here is my configuration.
![image](https://user-images.githubusercontent.com/46417244/201570569-bdf7d0a3-df73-4a9e-ab92-011890901833.png)

when my program run into a breakpoint like this, I thought I can directly input python sentence in console, and it will excute it . Just like debug JS in browser's DevTools's console.
![image](https://user-images.githubusercontent.com/46417244/201570639-10419904-b9c8-428a-98a9-07e22dfcfc8a.png)

but this error raised, and it seems to from pydev-odoo module.
![image](https://user-images.githubusercontent.com/46417244/201571043-7619da6e-f4ae-486e-8d96-a385edb11d3d.png)

plz help me out, thanks!

**Comment by trinhanhngoc** [comment]
1. `pydevd-odoo` is an extension of `pydevd` (https://github.com/fabioz/PyDev.Debugger) so any error can come from `pydevd` itself.
2. What is `data` in your context? Does the error also occur with other variables ?

**Comment by ohplz** [comment]
data is just a dict, but indeed, all the variables will triger up this error.
![image](https://user-images.githubusercontent.com/46417244/201585409-2fd96233-d363-44a7-8ed0-108ca5485736.png)

**Comment by trinhanhngoc** [comment]
What version of PyCharm are you using? I just tested on my machine (Odoo 14, PyCharm Pro 2022.2 with/without pydevd-odoo) and got no errors at all.

**Comment by trinhanhngoc** [comment]
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/11208291/201587778-852edb25-4fb5-4131-bb65-7cdd4ffd07a5.png">

**Comment by ohplz** [comment]
I'm using PyCharm 2022.3 EAP (Professional Edition) and also Odoo 14.

I'm still trying to resolve this problem, since your env hasn't this error, guess I have to solve it myself.

Thanks for your help! 

If I got sth, I'll get back to you!
