### ISSUE TITLE
Python type renderers﻿ when debugging with Pycharm

### ISSUE THREAD

**Issue by yotsubasuzu** [trinhanhngoc/pydevd-odoo#6]
Hi, im using Pycharm 2023.3.1 Build #PY-233.11799.298 on Windows OS 11, together with odoo-ide plugin, and when debugging odoo version 15 with pydevd-odoo the variables windows show like the image, above is package version 1.2.1 and below is package version 1.2.2

![image](https://github.com/odoo-ide/pydevd-odoo/assets/74945325/bc70cf02-fe40-415e-a21f-f96238049600)

**Comment by trinhanhngoc** [comment]
Hello @yotsubasuzu ,

Your screenshot is cropped, so I don't have enough information to debug. It's better if you have a code sample so I can reproduce the problem.

**Comment by yotsubasuzu** [comment]
now it's already working as intended ._. sorry for the trouble
when I encountered this was after I install the package, restart the server and started doing debug
and I think because of restarting Pycharm (and the computer also) solved the problem.
